---
title: "Sillence simpr simulation, with skewness"
output: html_output
---

Collapse all folds: Opt+Cmd+O
```{r setup}
library(dplyr)
library(simpr)
library(InteractionPoweR)

source("pwr_fns.R")
```

## Approach 1: From Reg Coefficients
```{r params}
##' first pass: should be analogous to model-specific simulation model output.
##' Generate multivariate normal using attenuated correlations for x1 and x2.
##' Generate y based on betas from power_interaction_r2 solution, roughly pasted below,
##' and error variance based on (1-r2)
##' 
##' Note: I may not actually need to do all this complex calculation myself.  
##' I could just use/leverage InteractionPowerR on a simple case 
##' with detailed_results = TRUE to get the appropriate coefficients!
##' 
##' 
p_all = power_interaction_r2(N = 500,
                              r.x1.y = -0.18,
                              r.x2.y = -0.03,
                              r.x1.x2 = 0.64,
                              r.x1x2.y = 0.1,
                              rel.y = 0.79,
                              rel.x1 = 0.89,
                              rel.x2 = 0.95,
                              alpha = 0.05,
                              detailed_results = TRUE)

p = p_all %>% 
  select(b1, b2, b3, obs.r.x1.x2,
         obs.r.x1.y, obs.r.x2.y, obs.r.x1x2.y) %>% 
  mutate(r2 = (b1*obs.r.x1.y) + (b2*obs.r.x2.y) + (b3*obs.r.x1x2.y),
         sigma = sqrt(1-r2))

str(p)
```
### Single simulation

```{r x_cor}
x_cor = matrix(c(1, 
                 p$obs.r.x1.x2,
                 p$obs.r.x1.x2, 1), 
               nrow = 2)
options(digits = 3)
x_cor
```


```{r}
## Simulate x1 and x2
set.seed(103)
x_matrix = MASS::mvrnorm(n = 100,
                         mu = c(0, 0), # mean vector
                         Sigma = x_cor # covariance matrix
) 
colnames(x_matrix) = c("x1", "x2")

## Simulate y based on x1 and x2
result = x_matrix %>%
  as_tibble %>% # convert to tibble
  mutate(y = ## Sum of coefficients * predictors + error
           p$b1 * x1 + 
           p$b2 * x2 + 
           p$b3 * x1 * x2 + 
           rnorm(100, sd = p$sigma)
         )
```

```{r}
head(x_matrix)
```
```{r}
result
```
```{r}
mod = lm(y ~ x1 * x2, data = result)
summary(mod)
```

### Simplified simpr simulation

```{r nornal_sim_100}
set.seed(1310)
normal_sim_100 =
  specify(x_matrix = c(x1, x2) ~ MASS::mvrnorm(n = 100, 
                                               mu = rep(0, 2),
                                               Sigma = x_cor),
          y = ~ p$b1 * x1 + 
            p$b2 * x2 + 
            p$b3 * x1 * x2 + 
            rnorm(100, sd = p$sigma)) %>% 
  generate(50) %>% 
  fit(lm =~ lm(y ~ x1*x2)) %>% 
  tidy_fits() 
```

```{r normal_sim_100_power}
normal_sim_100_power = normal_sim_100 %>% 
  filter(term %in% "x1:x2") %>% 
  summarize(pwr = mean(p.value < 0.05))
```

### Normal-based simulation -- simplified

```{r}
set.seed(3105)
normal_sim_vary_n = specify(preds = c(x1, x2) ~ MASS::mvrnorm(n = N, mu = rep(0, 2),
                             Sigma = x_cor),
              y = ~ p$b1 * x1 +
                p$b2 * x2 + 
                p$b3 * x1 * x2 + 
                rnorm(N, sd = p$sigma)) %>% 
  define(N = seq(500, 1500, by = 25)) %>% 
  generate(50) %>% 
  fit(lm =~ lm(y ~ x1*x2)) %>% 
  tidy_fits()
normal_sim_vary_n
```
```{r normal_sim_vary_n_power}
normal_sim_vary_n_power = normal_sim_vary_n %>% 
  group_by(N) %>% 
  filter(term %in% "x1:x2") %>% 
  summarize(pwr = mean(p.value < 0.05))
```

### Replicating the model-specific simulation in simpr
```{r future_stuff}
library(future)
plan(multisession, workers = availableCores() - 1)
```

```{r}
set.seed(310510)
normal_sim = specify(preds = c(x1, x2) ~ MASS::mvrnorm(n = N, mu = rep(0, 2),
                             Sigma = x_cor),
              y = ~ p$b1 * x1 +
                p$b2 * x2 + 
                p$b3 * x1 * x2 + 
                rnorm(N, sd = p$sigma)) %>% 
  define(N = seq(500, 1500, by = 25)) %>% 
  fit(lm =~ lm(y ~ x1*x2)) %>% 
  tidy_fits() %>% 
  generate(10000, .progress = TRUE) 
```

```{r}
normal_sim = readRDS("Sillence_simpr_normal.RDS")
normal_sim = normal_sim %>% rename(N = n)
```

```{r}
normal_sim_power = normal_sim %>% 
  group_by(N) %>% 
  filter(term %in% "x1:x2") %>% 
  summarize(pwr = mean(p.value < 0.05))
```

### Custom simulation with gamma error
```{r}
set.seed(310510)
gamma_sim = specify(preds = c(x1, x2) ~ MASS::mvrnorm(n = N, mu = rep(0, 2),
                             Sigma = x_cor),
              y = ~ p$b1 * x1 +
                p$b2 * x2 + 
                p$b3 * x1 * x2 + 
                rgamma(N, shape = 1, scale = p$sigma) - p$sigma) %>% 
  define(N = seq(500, 1500, by = 25)) %>% 
  fit(lm =~ lm(y ~ x1*x2)) %>% 
  tidy_fits() %>% 
  generate(10000, .progress = TRUE) 
```

```{r}
saveRDS(gamma_sim, file = "gamma_sim.RDS")
```


### Custom simulation with range restriction
```{r}
set.seed(316847)

range_sim = specify(preds = c(x1, x2) ~ MASS::mvrnorm(n = N, mu = rep(0, 2),
                             Sigma = x_cor),
              y = ~ p$b1 * x1 +
                p$b2 * x2 + 
                p$b3 * x1 * x2 + 
                rnorm(N, sd = p$sigma)) %>% 
  define(N = seq(500, 1500, by = 25)) %>% 
  per_sim() %>% 
  mutate(across(everything(), ~ case_when(
		  .x > 1 ~ 1,
	  .x < -1 ~ -1,
	  TRUE ~ .x))) %>%  
  fit(lm =~ lm(y ~ x1*x2)) %>% 
  tidy_fits() %>% 
  generate(10000, .progress = TRUE) 
```
